blog-system/Models/BlogPosts.cs
using System.ComponentModel.DataAnnotations;
using blog_system.Common;

namespace blog_system.Models
{
	public class BlogPost
	{
        // primary key
        public int Id { get; set; }

        [Required]
        [MaxLength(100)]
        public string Title { get; set; } = "";

        [Required]
        [MaxLength(10000)]
        public string? Body { get; set; } = "";

        [MaxLength(ApplicationSettings.UserNameMaxLength)]
        public string User { get; set; } = "";

        public DateTime Date { get; set; }

        // navigation property 
        public ICollection<Comment>? Comments { get; set; } = new List<Comment>();

        
    }
}

// Entity Framework

blog-system/ViewModels/BlogPostsViewModel.cs
using System;
using blog_system.Models;

namespace blog_system.ViewModels
{
	public class BlogPostsViewModel
	{

        public string Title { get; set; } = "";
        public string Body { get; set; } = "";
        public string CommentBody { get; set; } = "";
        public ICollection<BlogPost>? BlogPosts { get; set; }
        public ICollection<Comment>? Comments { get; set; }
        public string User { get; set; } = "testUser";
    }
}

blog-system/Controllers/BlogPostsController.cs
using Microsoft.AspNetCore.Mvc;
using blog_system.Data;
using Microsoft.EntityFrameworkCore;
using blog_system.ViewModels;
using blog_system.Models;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

//LINQ - language that .NET/C# uses to communicate to the database



namespace blog_system.Controllers
{
    public class BlogPostsController : Controller
    {

        private readonly BlogContext _context;

        public BlogPostsController(BlogContext context)
        {
            _context = context;
        }

        //GET: /blogposts/
        public IActionResult Index()
        {
            BlogPostsViewModel viewModel = new BlogPostsViewModel()
            {
                BlogPosts = _context.BlogPosts.ToList(),
                Comments = _context.Comments.ToList()
            };
            return View(viewModel);

        }

        public IActionResult NewPost()
        {
            return View();
        }

        //POST: /blogposts/new
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> NewPost(BlogPostsViewModel viewModel) //Can I bring 'bind' back into it?
        {
            if (ModelState.IsValid)
            {
                var blogpost = new BlogPost
                {
                    Body = viewModel.Body,
                    Title = viewModel.Title,
                    Date = DateTime.Now,
                    User = "testuser"
                };

                try
                {
                    _context.Update(blogpost);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    throw;
                }
                return RedirectToAction(nameof(Index));
            }
            return View();
        }


        //// GET: /blogposts/ 
        //public IActionResult Index(int? pageIndex, string sortBy) // int question mark means that it can be nullable
        //{
        //    if (!pageIndex.HasValue)
        //    {
        //        pageIndex = 1;
        //    }
        //    if (String.IsNullOrWhiteSpace(sortBy))
        //    {
        //        sortBy = "Date";
        //    }
        //    return Content(String.Format("pageIndex={0}&sortBy={1}", pageIndex, sortBy));
        //}

        ////GET: /blogposts/{year}/{month}/{day}
        //[Route("blogposts/{year:range(1900, 2024)}/{month:range(1,12)}/{day:range(1,31)}")] //colons are 'seperators' that allow us to add constraints
        //public IActionResult ByReleaseDate(int year, int month, int day)
        //{
        //    return Content(year + "/" + month + "/" + day);
        //}

        ////POST: /blogposts/new
        //[Route("blogposts/new")]
        //[HttpPost]
        //public IActionResult New()
        //{


        //}
    }
}

blog-system/Controllers/CommentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using blog_system.Data;
using blog_system.Models;
using blog_system.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace blog_system.Controllers
{
    public class CommentsController : Controller
    {

        private readonly BlogContext _context;

        public CommentsController(BlogContext context)
        {
            _context = context;
        }
        // GET: /<controller>/
        [HttpPost]
        //[AutoValidateAntiforgeryToken]
        public async Task<IActionResult> PostComment([FromBody] AddCommentViewModel input)
        {

            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);  // This will send a 400 response with the validation errors.
            }

            Comment comment = new Comment
            {
                Body = input.Body,
                User = "testUser",
                BlogPostId = input.BlogID

            };
            try
            {
                _context.Add(comment);
                await _context.SaveChangesAsync();
                return Json(new { success = true, message = "Comment added successfully!" });
            }
            catch (DbUpdateConcurrencyException)
            {
                return Json(new { success = false, message = "Comment not added" });
            }

        }
    }
}

blog-system/Views/BlogPosts/Index.cshtml
@model blog_system.ViewModels.BlogPostsViewModel

@{
    <h1>Blog Posts</h1>
    <ul>
        @if (Model.BlogPosts != null)
        {
            foreach (var post in Model.BlogPosts)
            {
                <li>
                    <ul>
                        <li>@post.Title</li>
                        <li>@post.Body</li>
                        @if (Model.Comments != null)
                        {
                            <li>
                                Comments:
                                <ul id="commentsList">
                                    @foreach (var comment in Model.Comments)
                                        @if (comment.BlogPostId == post.Id)
                                        {
                                            {
                                                <li>
                                                    <ul>
                                                        <li>User: @comment.User</li>
                                                        <li>Message: @comment.Body</li>
                                                        <li>Date: @comment.Date</li>
                                                    </ul>
                                                </li>
                                            }
                                        }
                                </ul>
                            </li>
                    }
                        <li>
                            <div class="form-group">
                                <label for="Comment">Comment:</label>
                                @Html.TextBoxFor(model => model.CommentBody, new { @class = "form-control", id = "commentContent" })
                                @Html.ValidationMessageFor(model => model.CommentBody, "", new { @class = "text-danger" })
                            </div>
                        </li>
                        <li>
                            Post as @Model.User
                        </li>
                        <li>
                            <button onClick="postComment('@post.Id','@DateTime.Now', '@Model.User')" class="btn btn-primary">Post</button>
                            <div id="success"></div>
                        </li>
                    </ul>
                </li>
            }
        }
    </ul>
}

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script>
function postComment(id, date, user) {

    var commentBody = $('#commentContent').val();

    $.ajax({
        url: '@Url.Action("PostComment", "Comments")',
        type: 'POST',
        contentType: 'application/json',
        data: JSON.stringify({
            Body: commentBody,
            BlogID: id
        }),
        success: function (res) {
            if (res.success) {
                $('#commentsList').append('<li><ul><li>User: ' + commentBody + '</li>' + '<li> Message:' + date + '</li>' + '<li> Date:' + user + '</li></ul></li>');
                $('#success').append('Comment posted!')
            }
            else {
                $('#success').append('Error posting comment')
            }
        },
        error: function (xhr) {
            console.log('Error posting comment: ' + xhr.statusText);
        }
    });

}
</script>

blog-system/Views/BlogPosts/NewPost.cshtml
@model blog_system.ViewModels.BlogPostsViewModel


@using (Html.BeginForm("NewPost", "BlogPosts", FormMethod.Post))
{
    <div class="form-group">
        <label for="Title">Title:</label>
        @Html.TextBoxFor(model => model.Title, new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
    </div>
    <div class="form-group">
        <label for="Post">Blog Post</label>
        @Html.TextBoxFor(model => model.Body, new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.Body, "", new { @class = "text-danger" })
    </div>
    <button type="submit" class="btn btn-primary">Post</button>
}

blog-system/Views/BlogPosts/Random.cshtml
@model blog_system.Models.BlogPost
@*

    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{

}


 @*When we use '@' - it's to go form

 ViewData is weakly typed and can store any time of data, so an object of the base class 'object' in  returned. The runtime does not know the specific type of object stored

 so we have to declare the type
    (this is old code that has beenr removed)


     *@

<h2>@Model.Title</h2>